### ISSUE TITLE
OS X error when running the command bin/build

### ISSUE THREAD

**Issue by matheboy** [Infinidat/relocatable-python#11]
I installed the dependencies and run the commands as required, but I get this error:
```
Traceback (most recent call last):
  File "bin/build", line 17, in <module>
    import scripts
  File "/Users/jav/relocatable-python/src/scripts/__init__.py", line 5, in <module>
    from infi.execute import execute_assert_success
  File "/Users/jav/relocatable-python/eggs/infi.execute-0.1.7-py2.7.egg/infi/execute/__init__.py", line 3, in <module>
    from .runner import local, through_ssh
  File "/Users/jav/relocatable-python/eggs/infi.execute-0.1.7-py2.7.egg/infi/execute/runner.py", line 7, in <module>
    from .result import Result
  File "/Users/jav/relocatable-python/eggs/infi.execute-0.1.7-py2.7.egg/infi/execute/result.py", line 1, in <module>
    from .waiting import wait_for_many_results, flush
  File "/Users/jav/relocatable-python/eggs/infi.execute-0.1.7-py2.7.egg/infi/execute/waiting.py", line 1, in <module>
    from .ioloop import IOLoop, time
  File "/Users/jav/relocatable-python/eggs/infi.execute-0.1.7-py2.7.egg/infi/execute/ioloop.py", line 13, in <module>
    if is_supported():
  File "/Users/jav/relocatable-python/eggs/infi.monotonic_time-0.1.7-py2.7.egg/infi/monotonic_time/__init__.py", line 29, in is_supported
    monotonic_time()
  File "/Users/jav/relocatable-python/eggs/infi.monotonic_time-0.1.7-py2.7.egg/infi/monotonic_time/__init__.py", line 24, in monotonic_time
    return time_from_monotonic(monotonic_clock())
  File "/Users/jav/relocatable-python/eggs/infi.monotonic_time-0.1.7-py2.7.egg/infi/monotonic_time/darwin.py", line 31, in monotonic_clock
    _init_library()
  File "/Users/jav/relocatable-python/eggs/infi.monotonic_time-0.1.7-py2.7.egg/infi/monotonic_time/darwin.py", line 20, in _init_library
    _libc = ctypes.CDLL("libc.dylib")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libc.dylib, 6): image not found
```

**Comment by wiggin15** [comment]
I suspect SIP is preventing the default MacOS Python executable from loading "libc.dylib" implicitly from `/usr/lib`. It appears the following doesn't work with the system Python:

    import ctypes
    ctypes.CDLL("libc.dylib")

but this does

    import ctypes
    ctypes.CDLL("/usr/lib/libc.dylib")

We will change `monotonic_time` to explicitly use the absolute path of libc.dylib.
In the meantime, the simplest workaround is to use virtualenv or install the latest version of Python using [brew](https://brew.sh/) - looks like SIP doesn't prevent non-system Python executables from loading libc.

**Comment by matheboy** [comment]
Thanx @wiggin15  for the quick answer. 
I tried brew but the recent changes do not replace the system python and got problems installing zc.buildout dependency as well. I may try virtualenv but I would prefer to try your change. I hope I doesn't take too long.

**Comment by amito** [comment]
Updated `infi.monotonic_time` in the global pypi. @matheboy, please see if `bin/build` works for you now.
Thanks.

**Comment by matheboy** [comment]
Hey is compiling now, is not finished yet, but at this point I can tell you the problem we were talking about is solved! 
Thanx a lot
